# Airline Passenger Satisfaction Analysis

## Project Introduction

This project focuses on the Airline Passenger Satisfaction dataset. The dataset contains information about airline passengers, their flight experience, and their overall satisfaction level.

The main goal of this project is to analyze the data, identify factors that affect passenger satisfaction, and build a Machine Learning model capable of predicting whether a passenger is satisfied or dissatisfied.

The project will include data exploration, data cleaning, feature analysis, data preprocessing, model building, and model evaluation.

---

# Step 1 - Initial Dataset Exploration

In this stage, the dataset is loaded using the Pandas library and a preliminary exploration of the data is performed.

The first five rows of the dataset are displayed, followed by an examination of the dataset dimensions and data types.

This step is important because it helps us understand the structure of the dataset and become familiar with the available features before performing further analysis and preprocessing.

In [4]:
import pandas as pd


df = pd.read_csv('train.csv')

print("--- The first 5 rows of the dataset ---")
display(df.head())

print("\n--- Data structure (rows, columns) ---")
print(df.shape)

print("\n--- General information about columns and data types ---")
df.info()

--- The first 5 rows of the dataset ---

,Unnamed: 0,id,Gender,Customer Type,Age,Type of Travel,Class,Flight Distance,Inflight wifi service,Departure/Arrival time convenient,...,Inflight entertainment,On-board service,Leg room service,Baggage handling,Checkin service,Inflight service,Cleanliness,Departure Delay in Minutes,Arrival Delay in Minutes,satisfaction
0,0,70172,Male,Loyal Customer,13,Personal Travel,Eco Plus,460,3,4,...,5,4,3,4,4,5,5,25,18.0,neutral or dissatisfied
1,1,5047,Male,disloyal Customer,25,Business travel,Business,235,3,2,...,1,1,5,3,1,4,1,1,6.0,neutral or dissatisfied
2,2,110028,Female,Loyal Customer,26,Business travel,Business,1142,2,2,...,5,4,3,4,4,4,5,0,0.0,satisfied
3,3,24026,Female,Loyal Customer,25,Business travel,Business,562,2,5,...,2,2,5,3,1,4,2,11,9.0,neutral or dissatisfied
4,4,119299,Male,Loyal Customer,61,Business travel,Business,214,3,3,...,3,3,4,4,3,3,3,0,0.0,satisfied

--- Data structure (rows, columns) ---
(103904, 25)

--- General information about columns and data types ---
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 103904 entries, 0 to 103903
Data columns (total 25 columns):
 #   Column                             Non-Null Count   Dtype
---  ------                             --------------   -----
 0   Unnamed: 0                         103904 non-null  int64
 1   id                                 103904 non-null  int64
 2   Gender                             103904 non-null  object
 3   Customer Type                      103904 non-null  object
 4   Age                                103904 non-null  int64
 5   Type of Travel                     103904 non-null  object
 6   Class                              103904 non-null  object
 7   Flight Distance                    103904 non-null  int64
 8   Inflight wifi service              103904 non-null  int64
 9   Departure/Arrival time convenient  103904 non-null  int64
 10  Ease of Online booking             103904 non-null  int64
 11  Gate location                      103904 non-null  int64
 12  Food and drink                     103904 non-null  int64
 13  Online boarding                    103904 non-null  int64
 14  Seat comfort                       103904 non-null  int64
 15  Inflight entertainment             103904 non-null  int64
 16  On-board service                   103904 non-null  int64
 17  Leg room service                   103904 non-null  int64
 18  Baggage handling                   103904 non-null  int64
 19  Checkin service                    103904 non-null  int64
 20  Inflight service                   103904 non-null  int64
 21  Cleanliness                        103904 non-null  int64
 22  Departure Delay in Minutes         103904 non-null  int64
 23  Arrival Delay in Minutes           103594 non-null  float64
 24  satisfaction                       103904 non-null  object
dtypes: float64(1), int64(19), object(5)
memory usage: 19.8+ MB

# Step 2 - Exploratory Data Analysis (EDA)

## Overview

After becoming familiar with the dataset structure, the next step is to perform an Exploratory Data Analysis (EDA).

The purpose of this stage is to gain a deeper understanding of the data by examining numerical and categorical features, reviewing basic statistical measures, and identifying potential data quality issues.

The analysis includes:

* Identifying numerical and categorical columns.
* Examining descriptive statistics such as mean, median, minimum, and maximum values.
* Detecting missing values in the dataset.
* Identifying unusual values or potential outliers.

Understanding the data at this stage is essential for making informed decisions during data preprocessing and model development.

In [12]:
num_cols = df.select_dtypes(include=['number']).columns.tolist()
cat_cols = df.select_dtypes(include=['object', 'category']).columns.tolist()

print("=== COLUMN TYPES IN DATASET ===")
print(f"Numerical columns ({len(num_cols)}): {num_cols}\n")
print(f"Categorical columns ({len(cat_cols)}): {cat_cols}")
print("-" * 60)

print("\n=== STATISTICAL SUMMARY FOR NUMERICAL COLUMNS ===")
display(df[num_cols].describe().T)
print("-" * 60)

print("\n=== CHECKING FOR MISSING VALUES (NULLs) ===")
missing_values = df.isnull().sum()
missing_only = missing_values[missing_values > 0]

if len(missing_only) == 0:
    print("Great! There are no missing values in this dataset.")
else:
    print("Columns with missing values and their respective counts:")
    print(missing_only)

=== COLUMN TYPES IN DATASET ===
Numerical columns (20): ['Unnamed: 0', 'id', 'Age', 'Flight Distance', 'Inflight wifi service', 'Departure/Arrival time convenient', 'Ease of Online booking', 'Gate location', 'Food and drink', 'Online boarding', 'Seat comfort', 'Inflight entertainment', 'On-board service', 'Leg room service', 'Baggage handling', 'Checkin service', 'Inflight service', 'Cleanliness', 'Departure Delay in Minutes', 'Arrival Delay in Minutes']

Categorical columns (5): ['Gender', 'Customer Type', 'Type of Travel', 'Class', 'satisfaction']
------------------------------------------------------------

=== STATISTICAL SUMMARY FOR NUMERICAL COLUMNS ===

,count,mean,std,min,25%,50%,75%,max
Unnamed: 0,103904.0,51951.500000,29994.645522,0.0,25975.75,51951.5,77927.25,103903.0
id,103904.0,64924.210502,37463.812252,1.0,32533.75,64856.5,97368.25,129880.0
Age,103904.0,39.379706,15.114964,7.0,27.00,40.0,51.00,85.0
Flight Distance,103904.0,1189.448375,997.147281,31.0,414.00,843.0,1743.00,4983.0
Inflight wifi service,103904.0,2.729683,1.327829,0.0,2.00,3.0,4.00,5.0
Departure/Arrival time convenient,103904.0,3.060296,1.525075,0.0,2.00,3.0,4.00,5.0
Ease of Online booking,103904.0,2.756901,1.398929,0.0,2.00,3.0,4.00,5.0
Gate location,103904.0,2.976883,1.277621,0.0,2.00,3.0,4.00,5.0
Food and drink,103904.0,3.202129,1.329533,0.0,2.00,3.0,4.00,5.0
Online boarding,103904.0,3.250375,1.349509,0.0,2.00,3.0,4.00,5.0
Seat comfort,103904.0,3.439396,1.319088,0.0,2.00,4.0,5.00,5.0
Inflight entertainment,103904.0,3.358158,1.332991,0.0,2.00,4.0,4.00,5.0
On-board service,103904.0,3.382363,1.288354,0.0,2.00,4.0,4.00,5.0
Leg room service,103904.0,3.351055,1.315605,0.0,2.00,4.0,4.00,5.0
Baggage handling,103904.0,3.631833,1.180903,1.0,3.00,4.0,5.00,5.0
Checkin service,103904.0,3.304290,1.265396,0.0,3.00,3.0,4.00,5.0
Inflight service,103904.0,3.640428,1.175663,0.0,3.00,4.0,5.00,5.0
Cleanliness,103904.0,3.286351,1.312273,0.0,2.00,3.0,4.00,5.0
Departure Delay in Minutes,103904.0,14.815618,38.230901,0.0,0.00,0.0,12.00,1592.0
Arrival Delay in Minutes,103594.0,15.178678,38.698682,0.0,0.00,0.0,13.00,1584.0

------------------------------------------------------------

=== CHECKING FOR MISSING VALUES (NULLs) ===
Columns with missing values and their respective counts:
Arrival Delay in Minutes    310
dtype: int64